DROP DATABASE IF EXISTS DATA_ANALYSIS_PROJ1;

CREATE DATABASE DATA_ANALYSIS_P1;

CREATE TABLE retail_sales(
transactions_id INT PRIMARY KEY,	
sale_date DATE,
sale_time TIME,	
customer_id INT,	
gender VARCHAR(15),	
age INT,	
category VARCHAR(50),	
quantiy	INT,
price_per_unit FLOAT,	
cogs FLOAT,	
total_sale FLOAT
);
SELECT * FROM
RETAIL_SALES;


select 
  count(*)
from retail_sales;

SELECT * FROM
RETAIL_SALES
WHERE
TRANSACTIONS_ID IS NULL
OR
SALE_DATE IS NULL
OR
SALE_TIME IS NULL
OR
CUSTOMER_ID IS NULL
OR
GENDER IS NULL
OR 
AGE IS NULL
OR
CATEGORY IS NULL
OR
QUANTIY IS NULL
OR
PRICE_PER_UNIT IS NULL
OR
COGS IS NULL
OR
TOTAL_SALE IS NULL;
-- HOW MANY SALES WE HAVE
SELECT COUNT(*) AS TOTAL_SALE 
FROM RETAIL_SALES;


SELECT COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_SALE
FROM RETAIL_SALES;

SELECT DISTINCT CATEGORY FROM RETAIL_SALES;

-- DATA ANALYSIS & BUSSINESS KEY PROBLEMS & ANSWERS

-- WRITE A SQL QUERY TO RETRIEVE ALL COLUMNS FOR SALES MADE ON 2009-06-22

SELECT * FROM
RETAIL_SALES
WHERE
SALE_DATE = '2009_06_22';
 
 -- write a sequel query to retrieve  all the transaction where category is "clothing" and the quantity sold is more than 10 in november 2004? 
 
SELECT *
FROM RETAIL_SALES
WHERE 
   CATEGORY = 'Clothing'
   AND
   DATE_FORMAT(SALE_DATE, '%Y-%M')
   AND
   QUANTIY >= 4;

-- WRITE A SQL QUERY TO CALCULATE SALE DATA (TOTAL_SALE) FOR EACH CATEGORY?
SELECT 
  CATEGORY,
  SUM(TOTAL_SALE) AS NET_SALE,
  COUNT(*) AS TOTAL_ORDERS
  FROM RETAIL_SALES
  GROUP BY 1;
-- WRITE THE SQL QUERY OF AVERAGE AGE OF CUSTOMERS FROM 'BEAUTY' CATEGORY?
SELECT 
  ROUND(AVG(AGE) , 2) AS AVG_AGE
FROM RETAIL_SALES
WHERE
  CATEGORY= 'BEAUTY';

-- write a sql query of all transactions where total_sale is greater than 1000?

SELECT * FROM RETAIL_SALES 
WHERE TOTAL_SALE > 1000;
 
 
 -- WRITE A SQL QUERY TO FIND OT ALL THE TRANSACTIONS(TRANSACTION_ID) MADE BY EACH GENDER IN EACH CATEGORY?
 
 SELECT
   CATEGORY,
   GENDER,
   COUNT(*) AS TOTAL_TRANS
FROM RETAIL_SALES   
GROUP 
   BY 
   CATEGORY,
   GENDER
ORDER BY 1; 

--- WRITE A SQL QUERY TO FIND OUT AVERAGE OF EACH MONTH AND FIND OUT BEST SELLING MONTH IN EACH YEAR?
SELECT
      YEAR,
      MONTH,
   AVG(TOTAL_SALE)
FROM
(  
SELECT 
   YEAR(SALE_DATE) ,
   MONTH(SALE_DATE),
   AVG(TOTAL_SALE) AS AVG_SALE,
   rank() over(partition by year(sale_date) order by avg(total_sale) desc) AS RANK_NUM
FROM RETAIL_SALES
GROUP BY 1,2
) AS T1
WHERE RANK_NUM = 1;

-- write a sql query to find out the top five customers based on high total_sales?
SELECT 
   CUSTOMER_ID,
   SUM(TOTAL_SALE) AS TOTAL_SALES
FROM RETAIL_SALES
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;  

-- WRITE A SQL QUERY TO FIND OUT UNIQUE CUSTOMERS BUYING ITEMS FROM EACH CATEGORY?

SELECT 
CATEGORY,
COUNT(DISTINCT(CUSTOMER_ID)) AS CNT_UNIQUE_CS
FROM RETAIL_SALES
GROUP BY CATEGORY;
 
 --- WRITE A SQL QUERY to CREATE EACH SHIFT AND NUMBER OF ORDERS(EXAMPLE = MORNING <= 12 , AFTERNOON BETWEEN 12& 17 AND EVENING > 17)?
WITH HOURLY_SALE
AS
(
SELECT * ,
CASE
    WHEN HOUR(SALE_TIME) < 12 THEN 'MORNING'
    WHEN HOUR(SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
    ELSE 'EVENING'
END AS SHIFT
FROM RETAIL_SALES
)
SELECT 
  SHIFT ,
  COUNT(*) AS TOTAL_ORDERS
FROM HOURLY_SALE
GROUP BY SHIFT;  
  

SELECT EXTRACT(HOUR FROM CURRENT_TIME);
 
 
 --- END OF PROJECT ----


 



